# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore ./ClassLibrary1/ClassLibrary1.csproj

    - name: Build
      run: dotnet build ./ClassLibrary1/ClassLibrary1.csproj -- configuration Release --no-restore

    - name: Pack
      run: dotnet pack ./ClassLibrary1/ClassLibrary1.csproj --configuration Release --no-build --output ../ClassLibrary1/ClassLibrary1.csproj/bin/Release

    - name: NuGet Push
      run: dotnet nuget push "./ClassLibrary1/ClassLibrary1.csproj/bin/Release/*.nupkg"--source "https://nuget.pkg.github.com/poyrazym/dnm" --skip-duplicate --api-key ${{ secrets.GITHUB_TOKEN }}
